# Generated by Django 4.2.7 on 2026-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('consultation_request', 'Consultation Request'), ('consultation_accepted', 'Consultation Accepted'), ('consultation_completed', 'Consultation Completed'), ('payment_success', 'Payment Successful'), ('wallet_credit', 'Wallet Credited'), ('booking_reminder', 'Booking Reminder'), ('new_review', 'New Review'), ('payout_processed', 'Payout Processed'), ('general', 'General')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
