# Generated by Django 4.2.7 on 2026-03-29 12:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'astrologer_availability',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AstrologerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('account_details', models.JSONField(help_text='Bank account or UPI details')),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'astrologer_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AstrologerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Public display name', max_length=100)),
                ('bio', models.TextField(help_text='Brief introduction about the astrologer')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('languages', models.JSONField(default=list, help_text='List of languages spoken')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verification_documents', models.JSONField(default=list, help_text='List of document URLs')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('chat_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('call_price', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('video_price', models.DecimalField(decimal_places=2, default=30.0, max_digits=6)),
                ('is_available', models.BooleanField(default=False)),
                ('availability_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy')], default='offline', max_length=20)),
                ('total_consultations', models.PositiveIntegerField(default=0)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'astrologer_profiles',
                'ordering': ['display_order', '-average_rating'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='specializations/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'specializations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AstrologerSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.PositiveIntegerField(default=3, help_text='1=Beginner, 5=Expert', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('astrologer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='astrologers.astrologerprofile')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrologers.specialization')),
            ],
            options={
                'db_table': 'astrologer_specializations',
            },
        ),
        migrations.CreateModel(
            name='AstrologerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('astrologer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='astrologers.astrologerprofile')),
            ],
            options={
                'db_table': 'astrologer_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
