# Generated by Django 4.2.7 on 2026-03-29 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('astrologers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologerreview',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation'),
        ),
    ]
