# Generated by Django 4.2.7 on 2026-03-29 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrologers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologerreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astrologer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astrologerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astrologer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astrologerprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_astrologers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astrologerpayout',
            name='astrologer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='astrologers.astrologerprofile'),
        ),
        migrations.AddField(
            model_name='astrologerpayout',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astrologeravailability',
            name='astrologer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='astrologers.astrologerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='astrologerspecialization',
            unique_together={('astrologer', 'specialization')},
        ),
        migrations.AddIndex(
            model_name='astrologerreview',
            index=models.Index(fields=['astrologer', '-created_at'], name='astrologer__astrolo_294389_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='astrologerreview',
            unique_together={('astrologer', 'user', 'consultation')},
        ),
        migrations.AddIndex(
            model_name='astrologerprofile',
            index=models.Index(fields=['verification_status', 'is_available'], name='astrologer__verific_4bde96_idx'),
        ),
        migrations.AddIndex(
            model_name='astrologerprofile',
            index=models.Index(fields=['is_featured', 'is_top_rated'], name='astrologer__is_feat_9b2622_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='astrologeravailability',
            unique_together={('astrologer', 'day_of_week', 'start_time')},
        ),
    ]
