# Generated by Django 4.2.7 on 2026-03-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologers', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologerprofile',
            name='call_price',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
    ]
