# Generated by Django 4.2.7 on 2026-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_sign', models.CharField(choices=[('aries', 'Aries'), ('taurus', 'Taurus'), ('gemini', 'Gemini'), ('cancer', 'Cancer'), ('leo', 'Leo'), ('virgo', 'Virgo'), ('libra', 'Libra'), ('scorpio', 'Scorpio'), ('sagittarius', 'Sagittarius'), ('capricorn', 'Capricorn'), ('aquarius', 'Aquarius'), ('pisces', 'Pisces')], max_length=20)),
                ('date', models.DateField()),
                ('general', models.TextField()),
                ('love', models.TextField(blank=True)),
                ('career', models.TextField(blank=True)),
                ('health', models.TextField(blank=True)),
                ('finance', models.TextField(blank=True)),
                ('lucky_number', models.PositiveIntegerField(blank=True, null=True)),
                ('lucky_color', models.CharField(blank=True, max_length=50)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_horoscopes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Kundli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(max_length=50)),
                ('planetary_positions', models.JSONField(default=dict)),
                ('houses', models.JSONField(default=dict)),
                ('ascendant', models.CharField(blank=True, max_length=50)),
                ('moon_sign', models.CharField(blank=True, max_length=50)),
                ('sun_sign', models.CharField(blank=True, max_length=50)),
                ('nakshatra', models.CharField(blank=True, max_length=50)),
                ('chart_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kundlis',
                'ordering': ['-created_at'],
            },
        ),
    ]
